import enum
class StateEvents(enum.Enum):
    NOPERSON = "NOPERSON"
    CROOKED = "CROOKED"
    DRINKING = "DRINKING"
    STRAIGHT = "STRAIGHT"
    PHONE = "PHONE"
    
    DR_TIMER_START = "DR_TIMER_START"
    DR_TIMER_STOP = "DR_TIMER_STOP"
    DR_TIMER_RESUME = "DR_TIMER_RESUME"
    DR_TIMER_PAUSE = "DR_TIMER_PAUSE"
    DR_TIMER_OVER = "DR_TIMER_OVER"

    WD_TIMER_START = "WD_TIMER_START"
    WD_TIMER_STOP = "WD_TIMER_STOP"
    WD_TIMER_RESUME = "WD_TIMER_RESUME"
    WD_TIMER_PAUSE = "WD_TIMER_PAUSE"
    WD_TIMER_OVER = "WD_TIMER_OVER"

    CR_TIMER_START = "CR_TIMER_START"
    CR_TIMER_STOP = "CR_TIMER_STOP"
    CR_TIMER_OVER = "CR_TIMER_OVER"

    PH_TIMER_START = "PH_TIMER_START"
    PH_TIMER_STOP = "PH_TIMER_STOP"
    PH_TIMER_OVER = "PH_TIMER_OVER"
    
class ActionsEvents(enum.Enum):
    AUDIO_DRINK = "AUDIO_DRINK"
    AUDIO_CROOKED = "AUDIO_CROOKED"
    AUDIO_PHONE = "AUDIO_PHONE"
    AUDIO_NOPERSON = "AUDIO_NOPERSON"
    AUDIO_WD_OPEN = "AUDIO_WD_OPEN"
    
class Topics(enum.Enum):
    TOPIC_TIMER = "timer"
    TOPIC_STATEMACHINE = "statemachine"
    TOPIC_ACTIONS = "actions"

    
    
    
